# Generated by Django 3.1.4 on 2021-05-10 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='books',
            new_name='Book',
        ),
    ]
